apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tk9cl8ccv-python 
  janus-idp.io/tekton: tk9cl8ccv-python
  backstage.io/kubernetes-id: tk9cl8ccv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tk9cl8ccv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml