apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tk9cl8ccv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tk9cl8ccv-python 
  name: tk9cl8ccv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tk9cl8ccv-python 
